// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MemoriesColumns holds the columns for the "memories" table.
	MemoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "tenant_id", Type: field.TypeString},
		{Name: "subject_id", Type: field.TypeString},
		{Name: "agent_id", Type: field.TypeString, Nullable: true},
		{Name: "session_id", Type: field.TypeString, Nullable: true},
		{Name: "scope", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "embedding", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "vector(1536)"}},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
	}
	// MemoriesTable holds the schema information for the "memories" table.
	MemoriesTable = &schema.Table{
		Name:       "memories",
		Columns:    MemoriesColumns,
		PrimaryKey: []*schema.Column{MemoriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "memory_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{MemoriesColumns[1]},
			},
			{
				Name:    "memory_tenant_id_subject_id",
				Unique:  false,
				Columns: []*schema.Column{MemoriesColumns[1], MemoriesColumns[2]},
			},
			{
				Name:    "memory_tenant_id_scope",
				Unique:  false,
				Columns: []*schema.Column{MemoriesColumns[1], MemoriesColumns[5]},
			},
			{
				Name:    "memory_tenant_id_type",
				Unique:  false,
				Columns: []*schema.Column{MemoriesColumns[1], MemoriesColumns[6]},
			},
			{
				Name:    "memory_tenant_id_subject_id_scope",
				Unique:  false,
				Columns: []*schema.Column{MemoriesColumns[1], MemoriesColumns[2], MemoriesColumns[5]},
			},
			{
				Name:    "memory_embedding",
				Unique:  false,
				Columns: []*schema.Column{MemoriesColumns[8]},
				Annotation: &entsql.IndexAnnotation{
					OpClass: "vector_l2_ops",
					Type:    "hnsw",
				},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MemoriesTable,
	}
)

func init() {
}
