// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omnimemory/ent/memory"
)

// MemoryCreate is the builder for creating a Memory entity.
type MemoryCreate struct {
	config
	mutation *MemoryMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *MemoryCreate) SetTenantID(v string) *MemoryCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetSubjectID sets the "subject_id" field.
func (_c *MemoryCreate) SetSubjectID(v string) *MemoryCreate {
	_c.mutation.SetSubjectID(v)
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *MemoryCreate) SetAgentID(v string) *MemoryCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_c *MemoryCreate) SetNillableAgentID(v *string) *MemoryCreate {
	if v != nil {
		_c.SetAgentID(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *MemoryCreate) SetSessionID(v string) *MemoryCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_c *MemoryCreate) SetNillableSessionID(v *string) *MemoryCreate {
	if v != nil {
		_c.SetSessionID(*v)
	}
	return _c
}

// SetScope sets the "scope" field.
func (_c *MemoryCreate) SetScope(v string) *MemoryCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetType sets the "type" field.
func (_c *MemoryCreate) SetType(v string) *MemoryCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *MemoryCreate) SetContent(v string) *MemoryCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetEmbedding sets the "embedding" field.
func (_c *MemoryCreate) SetEmbedding(v []float32) *MemoryCreate {
	_c.mutation.SetEmbedding(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *MemoryCreate) SetMetadata(v map[string]interface{}) *MemoryCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MemoryCreate) SetCreatedAt(v time.Time) *MemoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MemoryCreate) SetNillableCreatedAt(v *time.Time) *MemoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MemoryCreate) SetUpdatedAt(v time.Time) *MemoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MemoryCreate) SetNillableUpdatedAt(v *time.Time) *MemoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *MemoryCreate) SetExpiresAt(v time.Time) *MemoryCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *MemoryCreate) SetNillableExpiresAt(v *time.Time) *MemoryCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MemoryCreate) SetID(v string) *MemoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the MemoryMutation object of the builder.
func (_c *MemoryCreate) Mutation() *MemoryMutation {
	return _c.mutation
}

// Save creates the Memory in the database.
func (_c *MemoryCreate) Save(ctx context.Context) (*Memory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemoryCreate) SaveX(ctx context.Context) *Memory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemoryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := memory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := memory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemoryCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Memory.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := memory.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Memory.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubjectID(); !ok {
		return &ValidationError{Name: "subject_id", err: errors.New(`ent: missing required field "Memory.subject_id"`)}
	}
	if v, ok := _c.mutation.SubjectID(); ok {
		if err := memory.SubjectIDValidator(v); err != nil {
			return &ValidationError{Name: "subject_id", err: fmt.Errorf(`ent: validator failed for field "Memory.subject_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "Memory.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := memory.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Memory.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Memory.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := memory.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Memory.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Memory.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := memory.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Memory.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Memory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Memory.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := memory.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Memory.id": %w`, err)}
		}
	}
	return nil
}

func (_c *MemoryCreate) sqlSave(ctx context.Context) (*Memory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Memory.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemoryCreate) createSpec() (*Memory, *sqlgraph.CreateSpec) {
	var (
		_node = &Memory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memory.Table, sqlgraph.NewFieldSpec(memory.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(memory.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.SubjectID(); ok {
		_spec.SetField(memory.FieldSubjectID, field.TypeString, value)
		_node.SubjectID = value
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(memory.FieldAgentID, field.TypeString, value)
		_node.AgentID = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(memory.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(memory.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(memory.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(memory.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Embedding(); ok {
		_spec.SetField(memory.FieldEmbedding, field.TypeJSON, value)
		_node.Embedding = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(memory.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(memory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(memory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(memory.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// MemoryCreateBulk is the builder for creating many Memory entities in bulk.
type MemoryCreateBulk struct {
	config
	err      error
	builders []*MemoryCreate
}

// Save creates the Memory entities in the database.
func (_c *MemoryCreateBulk) Save(ctx context.Context) ([]*Memory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Memory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemoryCreateBulk) SaveX(ctx context.Context) []*Memory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
