// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omnimemory/ent/memory"
	"github.com/plexusone/omnimemory/ent/predicate"
)

// MemoryUpdate is the builder for updating Memory entities.
type MemoryUpdate struct {
	config
	hooks    []Hook
	mutation *MemoryMutation
}

// Where appends a list predicates to the MemoryUpdate builder.
func (_u *MemoryUpdate) Where(ps ...predicate.Memory) *MemoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *MemoryUpdate) SetTenantID(v string) *MemoryUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableTenantID(v *string) *MemoryUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetSubjectID sets the "subject_id" field.
func (_u *MemoryUpdate) SetSubjectID(v string) *MemoryUpdate {
	_u.mutation.SetSubjectID(v)
	return _u
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableSubjectID(v *string) *MemoryUpdate {
	if v != nil {
		_u.SetSubjectID(*v)
	}
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *MemoryUpdate) SetAgentID(v string) *MemoryUpdate {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableAgentID(v *string) *MemoryUpdate {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// ClearAgentID clears the value of the "agent_id" field.
func (_u *MemoryUpdate) ClearAgentID() *MemoryUpdate {
	_u.mutation.ClearAgentID()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MemoryUpdate) SetSessionID(v string) *MemoryUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableSessionID(v *string) *MemoryUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *MemoryUpdate) ClearSessionID() *MemoryUpdate {
	_u.mutation.ClearSessionID()
	return _u
}

// SetScope sets the "scope" field.
func (_u *MemoryUpdate) SetScope(v string) *MemoryUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableScope(v *string) *MemoryUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *MemoryUpdate) SetType(v string) *MemoryUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableType(v *string) *MemoryUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MemoryUpdate) SetContent(v string) *MemoryUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableContent(v *string) *MemoryUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *MemoryUpdate) SetEmbedding(v []float32) *MemoryUpdate {
	_u.mutation.SetEmbedding(v)
	return _u
}

// AppendEmbedding appends value to the "embedding" field.
func (_u *MemoryUpdate) AppendEmbedding(v []float32) *MemoryUpdate {
	_u.mutation.AppendEmbedding(v)
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *MemoryUpdate) ClearEmbedding() *MemoryUpdate {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MemoryUpdate) SetMetadata(v map[string]interface{}) *MemoryUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MemoryUpdate) ClearMetadata() *MemoryUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemoryUpdate) SetUpdatedAt(v time.Time) *MemoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *MemoryUpdate) SetExpiresAt(v time.Time) *MemoryUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableExpiresAt(v *time.Time) *MemoryUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *MemoryUpdate) ClearExpiresAt() *MemoryUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the MemoryMutation object of the builder.
func (_u *MemoryUpdate) Mutation() *MemoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := memory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemoryUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := memory.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Memory.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectID(); ok {
		if err := memory.SubjectIDValidator(v); err != nil {
			return &ValidationError{Name: "subject_id", err: fmt.Errorf(`ent: validator failed for field "Memory.subject_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := memory.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Memory.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := memory.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Memory.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := memory.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Memory.content": %w`, err)}
		}
	}
	return nil
}

func (_u *MemoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memory.Table, memory.Columns, sqlgraph.NewFieldSpec(memory.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(memory.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubjectID(); ok {
		_spec.SetField(memory.FieldSubjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(memory.FieldAgentID, field.TypeString, value)
	}
	if _u.mutation.AgentIDCleared() {
		_spec.ClearField(memory.FieldAgentID, field.TypeString)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(memory.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(memory.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(memory.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(memory.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(memory.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(memory.FieldEmbedding, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmbedding(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memory.FieldEmbedding, value)
		})
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(memory.FieldEmbedding, field.TypeJSON)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(memory.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(memory.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(memory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(memory.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(memory.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemoryUpdateOne is the builder for updating a single Memory entity.
type MemoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemoryMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *MemoryUpdateOne) SetTenantID(v string) *MemoryUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableTenantID(v *string) *MemoryUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetSubjectID sets the "subject_id" field.
func (_u *MemoryUpdateOne) SetSubjectID(v string) *MemoryUpdateOne {
	_u.mutation.SetSubjectID(v)
	return _u
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableSubjectID(v *string) *MemoryUpdateOne {
	if v != nil {
		_u.SetSubjectID(*v)
	}
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *MemoryUpdateOne) SetAgentID(v string) *MemoryUpdateOne {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableAgentID(v *string) *MemoryUpdateOne {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// ClearAgentID clears the value of the "agent_id" field.
func (_u *MemoryUpdateOne) ClearAgentID() *MemoryUpdateOne {
	_u.mutation.ClearAgentID()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MemoryUpdateOne) SetSessionID(v string) *MemoryUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableSessionID(v *string) *MemoryUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *MemoryUpdateOne) ClearSessionID() *MemoryUpdateOne {
	_u.mutation.ClearSessionID()
	return _u
}

// SetScope sets the "scope" field.
func (_u *MemoryUpdateOne) SetScope(v string) *MemoryUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableScope(v *string) *MemoryUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *MemoryUpdateOne) SetType(v string) *MemoryUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableType(v *string) *MemoryUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MemoryUpdateOne) SetContent(v string) *MemoryUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableContent(v *string) *MemoryUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *MemoryUpdateOne) SetEmbedding(v []float32) *MemoryUpdateOne {
	_u.mutation.SetEmbedding(v)
	return _u
}

// AppendEmbedding appends value to the "embedding" field.
func (_u *MemoryUpdateOne) AppendEmbedding(v []float32) *MemoryUpdateOne {
	_u.mutation.AppendEmbedding(v)
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *MemoryUpdateOne) ClearEmbedding() *MemoryUpdateOne {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MemoryUpdateOne) SetMetadata(v map[string]interface{}) *MemoryUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MemoryUpdateOne) ClearMetadata() *MemoryUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemoryUpdateOne) SetUpdatedAt(v time.Time) *MemoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *MemoryUpdateOne) SetExpiresAt(v time.Time) *MemoryUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableExpiresAt(v *time.Time) *MemoryUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *MemoryUpdateOne) ClearExpiresAt() *MemoryUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the MemoryMutation object of the builder.
func (_u *MemoryUpdateOne) Mutation() *MemoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the MemoryUpdate builder.
func (_u *MemoryUpdateOne) Where(ps ...predicate.Memory) *MemoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemoryUpdateOne) Select(field string, fields ...string) *MemoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Memory entity.
func (_u *MemoryUpdateOne) Save(ctx context.Context) (*Memory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemoryUpdateOne) SaveX(ctx context.Context) *Memory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := memory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemoryUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := memory.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Memory.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectID(); ok {
		if err := memory.SubjectIDValidator(v); err != nil {
			return &ValidationError{Name: "subject_id", err: fmt.Errorf(`ent: validator failed for field "Memory.subject_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := memory.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Memory.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := memory.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Memory.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := memory.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Memory.content": %w`, err)}
		}
	}
	return nil
}

func (_u *MemoryUpdateOne) sqlSave(ctx context.Context) (_node *Memory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memory.Table, memory.Columns, sqlgraph.NewFieldSpec(memory.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Memory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memory.FieldID)
		for _, f := range fields {
			if !memory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(memory.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubjectID(); ok {
		_spec.SetField(memory.FieldSubjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(memory.FieldAgentID, field.TypeString, value)
	}
	if _u.mutation.AgentIDCleared() {
		_spec.ClearField(memory.FieldAgentID, field.TypeString)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(memory.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(memory.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(memory.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(memory.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(memory.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(memory.FieldEmbedding, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmbedding(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memory.FieldEmbedding, value)
		})
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(memory.FieldEmbedding, field.TypeJSON)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(memory.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(memory.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(memory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(memory.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(memory.FieldExpiresAt, field.TypeTime)
	}
	_node = &Memory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
