// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/plexusone/omnimemory/ent/memory"
	"github.com/plexusone/omnimemory/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeMemory = "Memory"
)

// MemoryMutation represents an operation that mutates the Memory nodes in the graph.
type MemoryMutation struct {
	config
	op              Op
	typ             string
	id              *string
	tenant_id       *string
	subject_id      *string
	agent_id        *string
	session_id      *string
	scope           *string
	_type           *string
	content         *string
	embedding       *[]float32
	appendembedding []float32
	metadata        *map[string]interface{}
	created_at      *time.Time
	updated_at      *time.Time
	expires_at      *time.Time
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*Memory, error)
	predicates      []predicate.Memory
}

var _ ent.Mutation = (*MemoryMutation)(nil)

// memoryOption allows management of the mutation configuration using functional options.
type memoryOption func(*MemoryMutation)

// newMemoryMutation creates new mutation for the Memory entity.
func newMemoryMutation(c config, op Op, opts ...memoryOption) *MemoryMutation {
	m := &MemoryMutation{
		config:        c,
		op:            op,
		typ:           TypeMemory,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMemoryID sets the ID field of the mutation.
func withMemoryID(id string) memoryOption {
	return func(m *MemoryMutation) {
		var (
			err   error
			once  sync.Once
			value *Memory
		)
		m.oldValue = func(ctx context.Context) (*Memory, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Memory.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMemory sets the old Memory of the mutation.
func withMemory(node *Memory) memoryOption {
	return func(m *MemoryMutation) {
		m.oldValue = func(context.Context) (*Memory, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MemoryMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MemoryMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Memory entities.
func (m *MemoryMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MemoryMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MemoryMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Memory.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTenantID sets the "tenant_id" field.
func (m *MemoryMutation) SetTenantID(s string) {
	m.tenant_id = &s
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (m *MemoryMutation) TenantID() (r string, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the Memory entity.
// If the Memory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemoryMutation) OldTenantID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (m *MemoryMutation) ResetTenantID() {
	m.tenant_id = nil
}

// SetSubjectID sets the "subject_id" field.
func (m *MemoryMutation) SetSubjectID(s string) {
	m.subject_id = &s
}

// SubjectID returns the value of the "subject_id" field in the mutation.
func (m *MemoryMutation) SubjectID() (r string, exists bool) {
	v := m.subject_id
	if v == nil {
		return
	}
	return *v, true
}

// OldSubjectID returns the old "subject_id" field's value of the Memory entity.
// If the Memory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemoryMutation) OldSubjectID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSubjectID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSubjectID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSubjectID: %w", err)
	}
	return oldValue.SubjectID, nil
}

// ResetSubjectID resets all changes to the "subject_id" field.
func (m *MemoryMutation) ResetSubjectID() {
	m.subject_id = nil
}

// SetAgentID sets the "agent_id" field.
func (m *MemoryMutation) SetAgentID(s string) {
	m.agent_id = &s
}

// AgentID returns the value of the "agent_id" field in the mutation.
func (m *MemoryMutation) AgentID() (r string, exists bool) {
	v := m.agent_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAgentID returns the old "agent_id" field's value of the Memory entity.
// If the Memory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemoryMutation) OldAgentID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAgentID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAgentID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAgentID: %w", err)
	}
	return oldValue.AgentID, nil
}

// ClearAgentID clears the value of the "agent_id" field.
func (m *MemoryMutation) ClearAgentID() {
	m.agent_id = nil
	m.clearedFields[memory.FieldAgentID] = struct{}{}
}

// AgentIDCleared returns if the "agent_id" field was cleared in this mutation.
func (m *MemoryMutation) AgentIDCleared() bool {
	_, ok := m.clearedFields[memory.FieldAgentID]
	return ok
}

// ResetAgentID resets all changes to the "agent_id" field.
func (m *MemoryMutation) ResetAgentID() {
	m.agent_id = nil
	delete(m.clearedFields, memory.FieldAgentID)
}

// SetSessionID sets the "session_id" field.
func (m *MemoryMutation) SetSessionID(s string) {
	m.session_id = &s
}

// SessionID returns the value of the "session_id" field in the mutation.
func (m *MemoryMutation) SessionID() (r string, exists bool) {
	v := m.session_id
	if v == nil {
		return
	}
	return *v, true
}

// OldSessionID returns the old "session_id" field's value of the Memory entity.
// If the Memory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemoryMutation) OldSessionID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSessionID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSessionID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSessionID: %w", err)
	}
	return oldValue.SessionID, nil
}

// ClearSessionID clears the value of the "session_id" field.
func (m *MemoryMutation) ClearSessionID() {
	m.session_id = nil
	m.clearedFields[memory.FieldSessionID] = struct{}{}
}

// SessionIDCleared returns if the "session_id" field was cleared in this mutation.
func (m *MemoryMutation) SessionIDCleared() bool {
	_, ok := m.clearedFields[memory.FieldSessionID]
	return ok
}

// ResetSessionID resets all changes to the "session_id" field.
func (m *MemoryMutation) ResetSessionID() {
	m.session_id = nil
	delete(m.clearedFields, memory.FieldSessionID)
}

// SetScope sets the "scope" field.
func (m *MemoryMutation) SetScope(s string) {
	m.scope = &s
}

// Scope returns the value of the "scope" field in the mutation.
func (m *MemoryMutation) Scope() (r string, exists bool) {
	v := m.scope
	if v == nil {
		return
	}
	return *v, true
}

// OldScope returns the old "scope" field's value of the Memory entity.
// If the Memory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemoryMutation) OldScope(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldScope is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldScope requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldScope: %w", err)
	}
	return oldValue.Scope, nil
}

// ResetScope resets all changes to the "scope" field.
func (m *MemoryMutation) ResetScope() {
	m.scope = nil
}

// SetType sets the "type" field.
func (m *MemoryMutation) SetType(s string) {
	m._type = &s
}

// GetType returns the value of the "type" field in the mutation.
func (m *MemoryMutation) GetType() (r string, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Memory entity.
// If the Memory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemoryMutation) OldType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *MemoryMutation) ResetType() {
	m._type = nil
}

// SetContent sets the "content" field.
func (m *MemoryMutation) SetContent(s string) {
	m.content = &s
}

// Content returns the value of the "content" field in the mutation.
func (m *MemoryMutation) Content() (r string, exists bool) {
	v := m.content
	if v == nil {
		return
	}
	return *v, true
}

// OldContent returns the old "content" field's value of the Memory entity.
// If the Memory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemoryMutation) OldContent(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContent: %w", err)
	}
	return oldValue.Content, nil
}

// ResetContent resets all changes to the "content" field.
func (m *MemoryMutation) ResetContent() {
	m.content = nil
}

// SetEmbedding sets the "embedding" field.
func (m *MemoryMutation) SetEmbedding(f []float32) {
	m.embedding = &f
	m.appendembedding = nil
}

// Embedding returns the value of the "embedding" field in the mutation.
func (m *MemoryMutation) Embedding() (r []float32, exists bool) {
	v := m.embedding
	if v == nil {
		return
	}
	return *v, true
}

// OldEmbedding returns the old "embedding" field's value of the Memory entity.
// If the Memory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemoryMutation) OldEmbedding(ctx context.Context) (v []float32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmbedding is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmbedding requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmbedding: %w", err)
	}
	return oldValue.Embedding, nil
}

// AppendEmbedding adds f to the "embedding" field.
func (m *MemoryMutation) AppendEmbedding(f []float32) {
	m.appendembedding = append(m.appendembedding, f...)
}

// AppendedEmbedding returns the list of values that were appended to the "embedding" field in this mutation.
func (m *MemoryMutation) AppendedEmbedding() ([]float32, bool) {
	if len(m.appendembedding) == 0 {
		return nil, false
	}
	return m.appendembedding, true
}

// ClearEmbedding clears the value of the "embedding" field.
func (m *MemoryMutation) ClearEmbedding() {
	m.embedding = nil
	m.appendembedding = nil
	m.clearedFields[memory.FieldEmbedding] = struct{}{}
}

// EmbeddingCleared returns if the "embedding" field was cleared in this mutation.
func (m *MemoryMutation) EmbeddingCleared() bool {
	_, ok := m.clearedFields[memory.FieldEmbedding]
	return ok
}

// ResetEmbedding resets all changes to the "embedding" field.
func (m *MemoryMutation) ResetEmbedding() {
	m.embedding = nil
	m.appendembedding = nil
	delete(m.clearedFields, memory.FieldEmbedding)
}

// SetMetadata sets the "metadata" field.
func (m *MemoryMutation) SetMetadata(value map[string]interface{}) {
	m.metadata = &value
}

// Metadata returns the value of the "metadata" field in the mutation.
func (m *MemoryMutation) Metadata() (r map[string]interface{}, exists bool) {
	v := m.metadata
	if v == nil {
		return
	}
	return *v, true
}

// OldMetadata returns the old "metadata" field's value of the Memory entity.
// If the Memory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemoryMutation) OldMetadata(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMetadata is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMetadata requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMetadata: %w", err)
	}
	return oldValue.Metadata, nil
}

// ClearMetadata clears the value of the "metadata" field.
func (m *MemoryMutation) ClearMetadata() {
	m.metadata = nil
	m.clearedFields[memory.FieldMetadata] = struct{}{}
}

// MetadataCleared returns if the "metadata" field was cleared in this mutation.
func (m *MemoryMutation) MetadataCleared() bool {
	_, ok := m.clearedFields[memory.FieldMetadata]
	return ok
}

// ResetMetadata resets all changes to the "metadata" field.
func (m *MemoryMutation) ResetMetadata() {
	m.metadata = nil
	delete(m.clearedFields, memory.FieldMetadata)
}

// SetCreatedAt sets the "created_at" field.
func (m *MemoryMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *MemoryMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Memory entity.
// If the Memory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemoryMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *MemoryMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *MemoryMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *MemoryMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Memory entity.
// If the Memory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemoryMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *MemoryMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetExpiresAt sets the "expires_at" field.
func (m *MemoryMutation) SetExpiresAt(t time.Time) {
	m.expires_at = &t
}

// ExpiresAt returns the value of the "expires_at" field in the mutation.
func (m *MemoryMutation) ExpiresAt() (r time.Time, exists bool) {
	v := m.expires_at
	if v == nil {
		return
	}
	return *v, true
}

// OldExpiresAt returns the old "expires_at" field's value of the Memory entity.
// If the Memory object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MemoryMutation) OldExpiresAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpiresAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpiresAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpiresAt: %w", err)
	}
	return oldValue.ExpiresAt, nil
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (m *MemoryMutation) ClearExpiresAt() {
	m.expires_at = nil
	m.clearedFields[memory.FieldExpiresAt] = struct{}{}
}

// ExpiresAtCleared returns if the "expires_at" field was cleared in this mutation.
func (m *MemoryMutation) ExpiresAtCleared() bool {
	_, ok := m.clearedFields[memory.FieldExpiresAt]
	return ok
}

// ResetExpiresAt resets all changes to the "expires_at" field.
func (m *MemoryMutation) ResetExpiresAt() {
	m.expires_at = nil
	delete(m.clearedFields, memory.FieldExpiresAt)
}

// Where appends a list predicates to the MemoryMutation builder.
func (m *MemoryMutation) Where(ps ...predicate.Memory) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the MemoryMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *MemoryMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Memory, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *MemoryMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *MemoryMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Memory).
func (m *MemoryMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MemoryMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.tenant_id != nil {
		fields = append(fields, memory.FieldTenantID)
	}
	if m.subject_id != nil {
		fields = append(fields, memory.FieldSubjectID)
	}
	if m.agent_id != nil {
		fields = append(fields, memory.FieldAgentID)
	}
	if m.session_id != nil {
		fields = append(fields, memory.FieldSessionID)
	}
	if m.scope != nil {
		fields = append(fields, memory.FieldScope)
	}
	if m._type != nil {
		fields = append(fields, memory.FieldType)
	}
	if m.content != nil {
		fields = append(fields, memory.FieldContent)
	}
	if m.embedding != nil {
		fields = append(fields, memory.FieldEmbedding)
	}
	if m.metadata != nil {
		fields = append(fields, memory.FieldMetadata)
	}
	if m.created_at != nil {
		fields = append(fields, memory.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, memory.FieldUpdatedAt)
	}
	if m.expires_at != nil {
		fields = append(fields, memory.FieldExpiresAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MemoryMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case memory.FieldTenantID:
		return m.TenantID()
	case memory.FieldSubjectID:
		return m.SubjectID()
	case memory.FieldAgentID:
		return m.AgentID()
	case memory.FieldSessionID:
		return m.SessionID()
	case memory.FieldScope:
		return m.Scope()
	case memory.FieldType:
		return m.GetType()
	case memory.FieldContent:
		return m.Content()
	case memory.FieldEmbedding:
		return m.Embedding()
	case memory.FieldMetadata:
		return m.Metadata()
	case memory.FieldCreatedAt:
		return m.CreatedAt()
	case memory.FieldUpdatedAt:
		return m.UpdatedAt()
	case memory.FieldExpiresAt:
		return m.ExpiresAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MemoryMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case memory.FieldTenantID:
		return m.OldTenantID(ctx)
	case memory.FieldSubjectID:
		return m.OldSubjectID(ctx)
	case memory.FieldAgentID:
		return m.OldAgentID(ctx)
	case memory.FieldSessionID:
		return m.OldSessionID(ctx)
	case memory.FieldScope:
		return m.OldScope(ctx)
	case memory.FieldType:
		return m.OldType(ctx)
	case memory.FieldContent:
		return m.OldContent(ctx)
	case memory.FieldEmbedding:
		return m.OldEmbedding(ctx)
	case memory.FieldMetadata:
		return m.OldMetadata(ctx)
	case memory.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case memory.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case memory.FieldExpiresAt:
		return m.OldExpiresAt(ctx)
	}
	return nil, fmt.Errorf("unknown Memory field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MemoryMutation) SetField(name string, value ent.Value) error {
	switch name {
	case memory.FieldTenantID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantID(v)
		return nil
	case memory.FieldSubjectID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSubjectID(v)
		return nil
	case memory.FieldAgentID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAgentID(v)
		return nil
	case memory.FieldSessionID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSessionID(v)
		return nil
	case memory.FieldScope:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetScope(v)
		return nil
	case memory.FieldType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case memory.FieldContent:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContent(v)
		return nil
	case memory.FieldEmbedding:
		v, ok := value.([]float32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmbedding(v)
		return nil
	case memory.FieldMetadata:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMetadata(v)
		return nil
	case memory.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case memory.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case memory.FieldExpiresAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpiresAt(v)
		return nil
	}
	return fmt.Errorf("unknown Memory field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MemoryMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MemoryMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MemoryMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Memory numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MemoryMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(memory.FieldAgentID) {
		fields = append(fields, memory.FieldAgentID)
	}
	if m.FieldCleared(memory.FieldSessionID) {
		fields = append(fields, memory.FieldSessionID)
	}
	if m.FieldCleared(memory.FieldEmbedding) {
		fields = append(fields, memory.FieldEmbedding)
	}
	if m.FieldCleared(memory.FieldMetadata) {
		fields = append(fields, memory.FieldMetadata)
	}
	if m.FieldCleared(memory.FieldExpiresAt) {
		fields = append(fields, memory.FieldExpiresAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MemoryMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MemoryMutation) ClearField(name string) error {
	switch name {
	case memory.FieldAgentID:
		m.ClearAgentID()
		return nil
	case memory.FieldSessionID:
		m.ClearSessionID()
		return nil
	case memory.FieldEmbedding:
		m.ClearEmbedding()
		return nil
	case memory.FieldMetadata:
		m.ClearMetadata()
		return nil
	case memory.FieldExpiresAt:
		m.ClearExpiresAt()
		return nil
	}
	return fmt.Errorf("unknown Memory nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MemoryMutation) ResetField(name string) error {
	switch name {
	case memory.FieldTenantID:
		m.ResetTenantID()
		return nil
	case memory.FieldSubjectID:
		m.ResetSubjectID()
		return nil
	case memory.FieldAgentID:
		m.ResetAgentID()
		return nil
	case memory.FieldSessionID:
		m.ResetSessionID()
		return nil
	case memory.FieldScope:
		m.ResetScope()
		return nil
	case memory.FieldType:
		m.ResetType()
		return nil
	case memory.FieldContent:
		m.ResetContent()
		return nil
	case memory.FieldEmbedding:
		m.ResetEmbedding()
		return nil
	case memory.FieldMetadata:
		m.ResetMetadata()
		return nil
	case memory.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case memory.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case memory.FieldExpiresAt:
		m.ResetExpiresAt()
		return nil
	}
	return fmt.Errorf("unknown Memory field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MemoryMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MemoryMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MemoryMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MemoryMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MemoryMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MemoryMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MemoryMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Memory unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MemoryMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Memory edge %s", name)
}
