// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/plexusone/omnimemory/ent/memory"
	"github.com/plexusone/omnimemory/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	memoryFields := schema.Memory{}.Fields()
	_ = memoryFields
	// memoryDescTenantID is the schema descriptor for tenant_id field.
	memoryDescTenantID := memoryFields[1].Descriptor()
	// memory.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	memory.TenantIDValidator = memoryDescTenantID.Validators[0].(func(string) error)
	// memoryDescSubjectID is the schema descriptor for subject_id field.
	memoryDescSubjectID := memoryFields[2].Descriptor()
	// memory.SubjectIDValidator is a validator for the "subject_id" field. It is called by the builders before save.
	memory.SubjectIDValidator = memoryDescSubjectID.Validators[0].(func(string) error)
	// memoryDescScope is the schema descriptor for scope field.
	memoryDescScope := memoryFields[5].Descriptor()
	// memory.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	memory.ScopeValidator = memoryDescScope.Validators[0].(func(string) error)
	// memoryDescType is the schema descriptor for type field.
	memoryDescType := memoryFields[6].Descriptor()
	// memory.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	memory.TypeValidator = memoryDescType.Validators[0].(func(string) error)
	// memoryDescContent is the schema descriptor for content field.
	memoryDescContent := memoryFields[7].Descriptor()
	// memory.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	memory.ContentValidator = memoryDescContent.Validators[0].(func(string) error)
	// memoryDescCreatedAt is the schema descriptor for created_at field.
	memoryDescCreatedAt := memoryFields[10].Descriptor()
	// memory.DefaultCreatedAt holds the default value on creation for the created_at field.
	memory.DefaultCreatedAt = memoryDescCreatedAt.Default.(func() time.Time)
	// memoryDescUpdatedAt is the schema descriptor for updated_at field.
	memoryDescUpdatedAt := memoryFields[11].Descriptor()
	// memory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	memory.DefaultUpdatedAt = memoryDescUpdatedAt.Default.(func() time.Time)
	// memory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	memory.UpdateDefaultUpdatedAt = memoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// memoryDescID is the schema descriptor for id field.
	memoryDescID := memoryFields[0].Descriptor()
	// memory.IDValidator is a validator for the "id" field. It is called by the builders before save.
	memory.IDValidator = memoryDescID.Validators[0].(func(string) error)
}
